### PR TITLE
Blur on click outside

### PR DESCRIPTION
**Pull request by medienbaecker**
I added the following code to hide the color picker when you click outside:
```js
document.body.addEventListener('click', (e) => {
  if (!this.$el.contains(e.target)) {
    this.active = false;
  };
}); 
```
 Solves #10

### CODE REVIEW

**Comment by mrflix** [comment]
I'd love to have this in the core. I often get annoyed with color pickers that stay open.

**Comment by pstaender** [comment]
Hi, the issue is still relevant.

The fix from @medienbaecker works fine in current kirby 3.6.1.1. Is there a chance that this fix gets merged @TimOetting ?

**Comment by medienbaecker** [comment]
@pstaender I think this plugin has been abandoned. I'd suggest using https://github.com/hananils/kirby-colors instead. It works great.

**Comment by pstaender** [comment]
> @pstaender I think this plugin has been abandoned. I'd suggest using https://github.com/hananils/kirby-colors instead. It works great.

Didn't know that… I'll try it out. Thx for your quick answer!

**Pull request closed without merging**
